spring:
  application:
    name: user-center
  datasource:
    driver-name: com.mysql.cj.jdbc.Dirver
    url: jdbc:mysql://101.132.174.210:3306/user_center?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19182030
  session:
    timeout: 86400
server:
  port: 8080
  servlet:
    context-path: /api
# DataSource Config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)